@hostname = localhost
@port = 8010
@host = {{hostname}}:{{port}}
@contentType = application/json


###
GET http://{{host}}/ HTTP/1.1
content-type: {{contentType}}

{}

###
GET http://{{host}}/maintenance/delete_history_chrome HTTP/1.1
Content-type: {{contentType}}

{}

###
GET http://{{host}}/maintenance/clear_temp HTTP/1.1
Content-type: {{contentType}}

{}

###
GET http://{{host}}/maintenance/resources HTTP/1.1
Content-type: {{contentType}}

{}

